### ISSUE TITLE
Always show the Analying..., No result

### ISSUE THREAD

**Issue by Stan-Lin** [pankajarm/google-app-engine#1]
My google app engine site:  https://ai-app-242403.appspot.com/

I just git clone this project. And execute the "gcloud deploy app"

Always show the Analying..., I can't get any result.

Is anyone same with me? this situation

[https://imgur.com/mcmfAY0](url)

**Comment by pankajarm** [comment]
can you please retry deploying few times more with following docs. Other people were successfully able to deploy this same condo.

**Comment by sam-n-bell** [comment]
I had the same issue. It was fixed by changing the return statement in the analyze function to:

`return JSONResponse({'result': learn.predict(img)[0].obj})`
